const api = require("../../utils/api");

Page({
  data: { packages: [], packageForm: { id: "", name: "", lessonCount: 14, priceYuan: 1380, validityMonths: 5, description: "", sortOrder: 10, status: "ACTIVE" }, config: { courseTypes: [], pricingRules: [], coupons: [], coaches: [] }, course: { name: "", lessons: 14, description: "" }, price: { amount: "" }, coupon: { code: "", name: "", discountType: "PERCENT", discountValue: 10, minAmount: 0, totalLimit: 0, startAt: "2026-01-01", endAt: "2027-12-31" }, coachIndex: 0, typeIndex: 0, discountIndex: 0, discountLabels: ["按比例减免", "固定金额减免"], saving: "", loading: true, payment: null },
  onShow() { this.load(); },
  async load() { this.setData({ loading: true }); const [config, payment, packages] = await Promise.all([api.call("listCommerceConfig"), api.call("getPaymentReadiness"), api.call("listCoursePackages")]); this.setData({ packages, config: { ...config, pricingRules: config.pricingRules.map((item) => ({ ...item, amountYuan: (Number(item.amount || 0) / 100).toFixed(2) })) }, payment, loading: false }); },
  packageField(event) { this.setData({ [`packageForm.${event.currentTarget.dataset.key}`]: event.detail.value }); },
  editPackage(event) { const item = this.data.packages.find((row) => row.id === event.currentTarget.dataset.id); if (item) this.setData({ packageForm: { id: item.id, name: item.name, lessonCount: item.lessonCount, priceYuan: item.priceYuan, validityMonths: item.validityMonths, description: item.description || "", sortOrder: item.sortOrder || 0, status: item.status } }); },
  resetPackage() { this.setData({ packageForm: { id: "", name: "", lessonCount: 14, priceYuan: 1380, validityMonths: 5, description: "", sortOrder: 10, status: "ACTIVE" } }); },
  async savePackage() { this.setData({ saving: "package" }); try { await api.call("saveCoursePackage", { item: this.data.packageForm }); wx.showToast({ title: "套餐已保存" }); this.resetPackage(); await this.load(); } finally { this.setData({ saving: "" }); } },
  async packageStatus(event) { const id = event.currentTarget.dataset.id, status = event.currentTarget.dataset.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"; await api.call("setCoursePackageStatus", { id, status }); wx.showToast({ title: status === "ACTIVE" ? "已恢复销售" : "已停售" }); await this.load(); },
  field(event) { this.setData({ [`${event.currentTarget.dataset.form}.${event.currentTarget.dataset.key}`]: event.detail.value }); },
  coach(event) { this.setData({ coachIndex: Number(event.detail.value) }); }, type(event) { this.setData({ typeIndex: Number(event.detail.value) }); },
  discount(event) { const discountIndex = Number(event.detail.value); this.setData({ discountIndex, "coupon.discountType": discountIndex ? "FIXED" : "PERCENT" }); },
  date(event) { this.setData({ [`coupon.${event.currentTarget.dataset.key}`]: event.detail.value }); },
  async saveCourse() { this.setData({ saving: "course" }); try { await api.call("saveCourseType", { item: this.data.course }); this.setData({ course: { name: "", lessons: 14, description: "" } }); await this.load(); } finally { this.setData({ saving: "" }); } },
  async savePrice() { const coach = this.data.config.coaches[this.data.coachIndex], type = this.data.config.courseTypes[this.data.typeIndex]; if (!coach || !type) return wx.showToast({ title: "请先配置教练和课程类型", icon: "none" }); this.setData({ saving: "price" }); try { await api.call("savePricingRule", { item: { coachId: coach.id, courseTypeId: type.id, amount: this.data.price.amount } }); this.setData({ price: { amount: "" } }); await this.load(); } finally { this.setData({ saving: "" }); } },
  async saveCoupon() { this.setData({ saving: "coupon" }); try { await api.call("saveCoupon", { item: this.data.coupon }); this.setData({ "coupon.code": "", "coupon.name": "" }); await this.load(); } finally { this.setData({ saving: "" }); } }
});
