const api = require("../../utils/api");

Page({
  data: { role: "parent", orders: [], catalog: [], students: [], studentIndex: 0, catalogIndex: 0, couponCode: "", loading: true, creating: false, confirming: "", paying: "", payment: null },
  onLoad(options) { this.preferredStudentId = options.studentId || ""; }, onShow() { this.load(); },
  async load() { this.setData({ loading: true }); const context = await api.call("getContext"); const tasks = [api.call("listOrders")]; if (context.user.role !== "coach") tasks.push(api.call("listCoursePackages"), api.call("listStudents")); if (context.user.role === "admin") tasks.push(api.call("getPaymentReadiness")); const result = await Promise.all(tasks); const orders = result[0], catalog = (result[1] || []).filter((item) => item.status === "ACTIVE").map((item) => ({ ...item, displayName: `${item.name} · ${item.lessonCount}节 · ¥${item.priceYuan} · 激活后${item.validityMonths}个月` })), students = result[2] || []; const studentIndex = Math.max(0, students.findIndex((item) => item.id === this.preferredStudentId)); this.setData({ role: context.user.role, orders, catalog, students, studentIndex, payment: result[3] || null, loading: false }); },
  student(event) { this.setData({ studentIndex: Number(event.detail.value) }); }, catalog(event) { this.setData({ catalogIndex: Number(event.detail.value) }); }, coupon(event) { this.setData({ couponCode: event.detail.value }); },
  async create() { const student = this.data.students[this.data.studentIndex], item = this.data.catalog[this.data.catalogIndex]; if (!student || !item) return wx.showToast({ title: "暂无可购买套餐", icon: "none" }); const confirmed = await new Promise((resolve) => wx.showModal({ title: "确认购买", content: `学员：${student.name}\n套餐：${item.name}\n增加课时：${item.lessonCount}节\n金额：¥${item.priceYuan}\n有效期：首次正式消课后${item.validityMonths}个月`, success: (result) => resolve(result.confirm) })); if (!confirmed) return; this.setData({ creating: true }); try { const result = await api.call("createOrder", { studentId: student.id, packageId: item.id, couponCode: this.data.couponCode }); wx.showModal({ title: "订单已创建", content: result.paymentConfigured ? `应付 ¥${result.amountYuan}，请继续微信支付。` : "微信支付暂未开通，请联系俱乐部。", showCancel: false }); this.setData({ couponCode: "" }); await this.load(); } finally { this.setData({ creating: false }); } },
  requestPayment(options) { return new Promise((resolve, reject) => wx.requestPayment({ ...options, success: resolve, fail: reject })); },
  async pay(event) { const id = event.currentTarget.dataset.id; if (this.data.paying) return; this.setData({ paying: id }); try { const payment = await api.call("createWechatPayment", { id }); if (!payment.configured) return wx.showModal({ title: "微信支付暂未开通", content: "请联系南联俱乐部工作人员。", showCancel: false }); if (payment.freeOrder || payment.alreadyPaid) { await this.load(); return; } const paymentOrderId = payment.orderId || id; await this.requestPayment({ timeStamp: payment.timeStamp, nonceStr: payment.nonceStr, package: payment.package, signType: payment.signType, paySign: payment.paySign }); const result = await api.call("queryWechatPayment", { id: paymentOrderId }); wx.showModal({ title: result.paid ? "支付成功" : "支付结果确认中", content: result.paid ? "课程课时已经到账。" : (result.reviewRequired ? "支付确认异常，请联系俱乐部工作人员。" : "支付状态确认中，请稍后刷新。"), showCancel: false }); await this.load(); } catch (error) { if (!String(error.errMsg || error.message || "").includes("cancel")) wx.showToast({ title: "支付状态确认中，请稍后刷新", icon: "none" }); } finally { this.setData({ paying: "" }); } },
  async confirm(event) { const id = event.currentTarget.dataset.id; wx.showModal({ title: "确认线下转账到账？", content: "确认后将立即增加课时，请填写收款备注。", editable: true, placeholderText: "必填：收款方式、时间或流水说明", success: async (result) => { if (!result.confirm) return; const note = String(result.content || "").trim(); if (!note) return wx.showToast({ title: "请填写收款备注", icon: "none" }); this.setData({ confirming: id }); try { await api.call("confirmOrderPayment", { id, paymentMethod: "OFFLINE_TRANSFER", note }); wx.showToast({ title: "已确认到账" }); await this.load(); } finally { this.setData({ confirming: "" }); } } }); }
});
