const api = require("../../utils/api");

Page({
  data: { role: "parent", orders: [], catalog: [], students: [], studentIndex: 0, catalogIndex: 0, couponCode: "", loading: true, creating: false, confirming: "", paying: "", payment: null },
  onLoad(options) { this.preferredStudentId = options.studentId || ""; }, onShow() { this.load(); },
  async load() { this.setData({ loading: true }); const context = await api.call("getContext"); const tasks = [api.call("listOrders")]; if (context.user.role !== "coach") tasks.push(api.call("listCatalog"), api.call("listStudents")); if (context.user.role === "admin") tasks.push(api.call("getPaymentReadiness")); const result = await Promise.all(tasks); const orders = result[0], catalog = (result[1] || []).map((item) => ({ ...item, displayName: `${item.coach.name} · ${item.courseType.name} · ¥${item.amountYuan}` })), students = result[2] || []; const studentIndex = Math.max(0, students.findIndex((item) => item.id === this.preferredStudentId)); this.setData({ role: context.user.role, orders, catalog, students, studentIndex, payment: result[3] || null, loading: false }); },
  student(event) { this.setData({ studentIndex: Number(event.detail.value) }); }, catalog(event) { this.setData({ catalogIndex: Number(event.detail.value) }); }, coupon(event) { this.setData({ couponCode: event.detail.value }); },
  async create() { const student = this.data.students[this.data.studentIndex], item = this.data.catalog[this.data.catalogIndex]; if (!student || !item) return wx.showToast({ title: "暂无可购买课程", icon: "none" }); this.setData({ creating: true }); try { const result = await api.call("createOrder", { studentId: student.id, pricingRuleId: item.id, couponCode: this.data.couponCode }); wx.showModal({ title: "订单已创建", content: result.paymentConfigured ? `应付 ¥${result.amountYuan}，请继续微信支付。` : `应付 ¥${result.amountYuan}。测试阶段请由管理员确认到账；配置商户参数后启用微信支付。`, showCancel: false }); this.setData({ couponCode: "" }); await this.load(); } finally { this.setData({ creating: false }); } },
  requestPayment(options) { return new Promise((resolve, reject) => wx.requestPayment({ ...options, success: resolve, fail: reject })); },
  async pay(event) { const id = event.currentTarget.dataset.id; if (this.data.paying) return; this.setData({ paying: id }); try { const payment = await api.call("createWechatPayment", { id }); if (!payment.configured) return wx.showModal({ title: "微信支付尚未配置", content: `缺少云函数环境变量：${payment.missing.join("、")}`, showCancel: false }); if (payment.freeOrder || payment.alreadyPaid) { await this.load(); return; } await this.requestPayment({ timeStamp: payment.timeStamp, nonceStr: payment.nonceStr, package: payment.package, signType: payment.signType, paySign: payment.paySign }); const result = await api.call("queryWechatPayment", { id }); wx.showModal({ title: result.paid ? "支付成功" : "支付结果确认中", content: result.paid ? "课程课时已经到账。" : (result.tradeStateDesc || "请稍后在订单页刷新查询。"), showCancel: false }); await this.load(); } catch (error) { if (!String(error.errMsg || error.message || "").includes("cancel")) wx.showToast({ title: error.message || "支付失败", icon: "none" }); } finally { this.setData({ paying: "" }); } },
  async confirm(event) { const id = event.currentTarget.dataset.id; wx.showModal({ title: "确认已经到账？", content: "确认后将立即增加对应课时，请核对线下收款记录。", success: async (result) => { if (!result.confirm) return; this.setData({ confirming: id }); try { await api.call("confirmOrderPayment", { id, paymentMethod: "MANUAL" }); wx.showToast({ title: "已确认到账" }); await this.load(); } finally { this.setData({ confirming: "" }); } } }); }
});
