const api = require("../../utils/api");
function offset(value, days) { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
function groups(items) { const map = new Map(); (items || []).forEach((item) => { if (!map.has(item.date)) map.set(item.date, { date: item.date, items: [] }); map.get(item.date).items.push(item); }); return [...map.values()]; }
Page({
  data: { loading: true, error: "", date: "", choices: [], choiceIndex: 0, studentId: "", joinedClassNames: "", timetable: { items: [], stats: {} }, groups: [] },
  onLoad() { this.setData({ date: new Date().toISOString().slice(0, 10) }); }, onShow() { this.load(true); }, onPullDownRefresh() { this.load(false); },
  async load(refreshFamily = false) { if (!this.data.date) return; this.setData({ loading: true, error: "" }); try { let choices = this.data.choices, studentId = this.data.studentId; if (refreshFamily || !choices.length) { const family = await api.call("getFamilyContext", { activeStudentId: getApp().globalData.activeStudentId || wx.getStorageSync("activeStudentId") }); choices = [{ id: "ALL", name: "全部孩子" }, ...(family.students || [])]; studentId = studentId || family.activeStudentId || (choices[1] || {}).id || "ALL"; } const timetable = await api.call("getUnifiedTimetable", { date: this.data.date, studentId }); const selected = studentId === "ALL" ? choices.slice(1) : choices.filter((row) => row.id === studentId), joinedClassNames = [...new Set(selected.flatMap((row) => String(row.classNames || "").split("、")).filter(Boolean))].join("、"); this.setData({ choices, choiceIndex: Math.max(0, choices.findIndex((row) => row.id === studentId)), studentId, joinedClassNames, timetable, groups: groups(timetable.items), loading: false }); } catch (error) { this.setData({ loading: false, error: "课表云端服务尚未更新，请部署新版 clubApi 后重试" }); } finally { wx.stopPullDownRefresh(); } },
  student(event) { const choiceIndex = Number(event.detail.value), studentId = this.data.choices[choiceIndex].id; if (studentId !== "ALL") { getApp().globalData.activeStudentId = studentId; wx.setStorageSync("activeStudentId", studentId); } this.setData({ choiceIndex, studentId }, () => this.load(false)); },
  previous() { this.setData({ date: offset(this.data.timetable.startDate || this.data.date, -7) }, () => this.load(false)); }, next() { this.setData({ date: offset(this.data.timetable.startDate || this.data.date, 7) }, () => this.load(false)); }, current() { this.setData({ date: new Date().toISOString().slice(0, 10) }, () => this.load(false)); },
  open(event) { if (event.currentTarget.dataset.type === "TRAINING") wx.navigateTo({ url: `/pages/session-detail/index?id=${event.currentTarget.dataset.id}&studentId=${event.currentTarget.dataset.student}` }); }
});
