const STATUS_LABELS = { NEW: "新线索", CONTACTED: "已联系", TRIAL_SCHEDULED: "已预约体验课", TRIAL_COMPLETED: "已体验", INTERESTED: "意向报名", WON: "已成交", LOST: "未成交", PUBLIC: "公海" };
const TRIAL_STATUS_LABELS = { SCHEDULED: "已预约", COMPLETED: "已完成", NO_SHOW: "未到", CANCELLED: "已取消" };
const SOURCES = ["微信群", "朋友圈", "公众号", "抖音", "视频号", "老学员转介绍", "朋友介绍", "线下活动", "学校合作", "电话咨询", "自然到店", "其他"];
const INTENTIONS = ["A", "B", "C"];
const METHODS = ["电话", "微信", "面谈", "短信", "其他"];
const RESULTS = ["未接通", "已联系", "继续考虑", "预约体验课", "价格咨询", "等待回复", "意向报名", "无意向", "其他"];
const COACHES = [{ id: "coach1", name: "游导" }, { id: "coach2", name: "王蒋生" }, { id: "coach3", name: "张教练" }];

function dateOnly(value) { return String(value || "").slice(0, 10); }
function addDays(date, days) { const value = new Date(`${dateOnly(date)}T12:00:00`); value.setDate(value.getDate() + days); return value.toISOString().slice(0, 10); }
function ageOf(birthday, now) { if (!birthday) return "-"; const birth = new Date(`${birthday}T00:00:00`); const current = new Date(`${dateOnly(now)}T00:00:00`); let age = current.getFullYear() - birth.getFullYear(); if (current < new Date(current.getFullYear(), birth.getMonth(), birth.getDate())) age -= 1; return Math.max(0, age); }
function isToday(value, today) { return dateOnly(value) === dateOnly(today); }
function isMonth(value, today) { return dateOnly(value).slice(0, 7) === dateOnly(today).slice(0, 7); }
function normalizedMobile(value) { return String(value || "").replace(/\D/g, ""); }

function demo(today) {
  const rows = [
    ["l1", "王小明", "男", "2018-05-12", "王先生", "13800001001", "朋友圈", "A", "NEW", "coach3", "张教练", 0, "U8兴趣班"],
    ["l2", "陈子墨", "男", "2017-09-03", "陈女士", "13800001002", "微信群", "B", "NEW", "coach1", "游导", 1, "17/18精英班"],
    ["l3", "林雨桐", "女", "2019-03-22", "林先生", "13800001003", "学校合作", "C", "NEW", "coach2", "王蒋生", 3, "兴趣成长班"],
    ["l4", "周浩然", "男", "2018-11-18", "周女士", "13800001004", "老学员转介绍", "A", "CONTACTED", "coach1", "游导", -2, "17/18精英班"],
    ["l5", "郑安琪", "女", "2017-04-09", "郑先生", "13800001005", "视频号", "B", "CONTACTED", "coach2", "王蒋生", 0, "兴趣成长班"],
    ["l6", "叶晨阳", "男", "2019-08-15", "叶女士", "13800001006", "朋友圈", "B", "CONTACTED", "coach3", "张教练", 2, "U8兴趣班"],
    ["l7", "徐嘉佑", "男", "2018-02-06", "徐先生", "13800001007", "学校合作", "A", "TRIAL_SCHEDULED", "coach1", "游导", 1, "17/18精英班"],
    ["l8", "胡一诺", "女", "2016-12-17", "胡女士", "13800001008", "公众号", "B", "TRIAL_SCHEDULED", "coach2", "王蒋生", 2, "15/16精英班"],
    ["l9", "戴梓豪", "男", "2019-06-28", "戴先生", "13800001009", "抖音", "C", "TRIAL_SCHEDULED", "coach3", "张教练", 3, "兴趣成长班"],
    ["l10", "金沐辰", "男", "2017-10-11", "金女士", "13800001010", "老学员转介绍", "A", "TRIAL_COMPLETED", "coach1", "游导", 1, "17/18精英班"],
    ["l11", "方可欣", "女", "2018-07-01", "方先生", "13800001011", "线下活动", "B", "TRIAL_COMPLETED", "coach2", "王蒋生", 1, "兴趣成长班"],
    ["l12", "吴天乐", "男", "2016-05-19", "吴女士", "13800001012", "学校合作", "A", "INTERESTED", "coach3", "张教练", 0, "15/16精英班"],
    ["l13", "朱星宇", "男", "2017-01-30", "朱先生", "13800001013", "朋友介绍", "A", "INTERESTED", "coach1", "游导", 1, "17/18精英班"],
    ["l14", "蒋睿", "男", "2018-03-14", "蒋女士", "13800001014", "老学员转介绍", "A", "WON", "coach1", "游导", 0, "17/18精英班"],
    ["l15", "谢语萱", "女", "2016-09-27", "谢先生", "13800001015", "学校合作", "B", "WON", "coach2", "王蒋生", 0, "15/16精英班"]
  ];
  const leads = rows.map((row, index) => ({ id: row[0], childName: row[1], gender: row[2], birthday: row[3], parentName: row[4], mobile: row[5], wechat: `nanlian${index + 1}`, school: index % 2 ? "瓯北中心小学" : "永嘉三幼", grade: index % 3 ? "小学" : "幼儿园", source: row[6], sourceDetail: "V3演示数据", intentionLevel: row[7], status: row[8], ownerCoachId: row[9], ownerCoachName: row[10], nextFollowUpAt: `${addDays(today, row[11])} 15:00`, lastFollowUpAt: index > 2 ? `${addDays(today, -1 - index % 4)} 16:00` : "", interestedProgram: row[12], trialStatus: row[8].startsWith("TRIAL") ? row[8] : "", tags: row[7] === "A" ? ["重点客户"] : [], remark: "南联招生CRM演示线索", createdBy: "admin", createdAt: `${addDays(today, -index - 1)} 10:00`, updatedAt: `${addDays(today, -Math.min(index, 3))} 10:00`, convertedStudentId: row[8] === "WON" ? (index === 13 ? "s1" : "s3") : "", convertedAt: row[8] === "WON" ? `${addDays(today, -2)} 12:00` : "", dealAmount: row[8] === "WON" ? (index === 13 ? 1980 : 1380) : 0 }));
  const leadFollowUps = leads.slice(3, 13).map((lead, index) => ({ id: `lf${index + 1}`, leadId: lead.id, method: index % 2 ? "微信" : "电话", result: lead.status === "INTERESTED" ? "意向报名" : lead.status === "TRIAL_SCHEDULED" ? "预约体验课" : "已联系", content: index % 2 ? "家长希望先了解训练安排和教练配置。" : "已沟通孩子情况，约定下一次联系时间。", nextFollowUpAt: lead.nextFollowUpAt, operatorId: lead.ownerCoachId, operatorName: lead.ownerCoachName, createdAt: lead.lastFollowUpAt || lead.createdAt }));
  const trialBookings = [
    { id: "tb1", leadId: "l7", childName: "徐嘉佑", classId: "c1718", className: "17/18精英班", sessionId: "se1", coachId: "coach1", coachName: "游导", venueName: "三江南联球场", trialDate: dateOnly(today), status: "SCHEDULED", attendanceStatus: "unmarked" },
    { id: "tb2", leadId: "l8", childName: "胡一诺", classId: "c1516", className: "15/16精英班", sessionId: "se3", coachId: "coach2", coachName: "王蒋生", venueName: "瓯北中心小学", trialDate: addDays(today, 1), status: "SCHEDULED", attendanceStatus: "unmarked" },
    { id: "tb3", leadId: "l9", childName: "戴梓豪", classId: "cinterest", className: "兴趣成长班", sessionId: "", coachId: "coach3", coachName: "张教练", venueName: "瓯北中心小学", trialDate: addDays(today, 2), status: "SCHEDULED", attendanceStatus: "unmarked" },
    { id: "tb4", leadId: "l10", childName: "金沐辰", classId: "c1718", className: "17/18精英班", sessionId: "history1", coachId: "coach1", coachName: "游导", venueName: "三江南联球场", trialDate: addDays(today, -2), status: "COMPLETED", attendanceStatus: "present", feedback: { attitude: 5, coordination: 4, ballSense: 4, understanding: 4, integration: 5, enthusiasm: 5, summary: "适应较快，建议进入17/18精英班。" }, recommendedClassId: "c1718" },
    { id: "tb5", leadId: "l11", childName: "方可欣", classId: "cinterest", className: "兴趣成长班", sessionId: "history2", coachId: "coach2", coachName: "王蒋生", venueName: "瓯北中心小学", trialDate: addDays(today, -1), status: "COMPLETED", attendanceStatus: "present", feedback: { attitude: 4, coordination: 4, ballSense: 3, understanding: 4, integration: 4, enthusiasm: 4, summary: "训练积极，建议从兴趣成长班开始。" }, recommendedClassId: "cinterest" }
  ].map((item, index) => ({ ...item, remark: "V3体验课演示", createdBy: "admin", createdAt: `${addDays(today, -index - 1)} 09:00`, updatedAt: `${addDays(today, -Math.min(index, 1))} 18:00` }));
  return { leads, leadFollowUps, trialBookings };
}

function ensure(data, today) {
  if (!Array.isArray(data.leads)) Object.assign(data, demo(today));
  if (!Array.isArray(data.leadFollowUps)) data.leadFollowUps = [];
  if (!Array.isArray(data.trialBookings)) data.trialBookings = [];
  return data;
}
function canAccessLead(lead, role, userId) { return role === "admin" || (role === "coach" && (lead.ownerCoachId === userId || lead.status === "PUBLIC")); }
function decorateLead(data, lead, today) {
  const next = String(lead.nextFollowUpAt || ""); const diff = next ? Math.floor((new Date(`${dateOnly(today)}T00:00:00`) - new Date(next.replace(" ", "T"))) / 86400000) : 0;
  const nextDate = dateOnly(next); const daysAhead = nextDate ? Math.ceil((new Date(`${nextDate}T00:00:00`) - new Date(`${dateOnly(today)}T00:00:00`)) / 86400000) : null;
  const dueBucket = daysAhead === null ? "none" : daysAhead < 0 ? "overdue" : daysAhead === 0 ? "today" : daysAhead <= 3 ? "threeDays" : daysAhead <= 7 ? "sevenDays" : "later";
  return { ...lead, age: ageOf(lead.birthday, today), statusLabel: STATUS_LABELS[lead.status] || lead.status, intentionLabel: `${lead.intentionLevel || "C"}级`, intentionClass: String(lead.intentionLevel || "C").toLowerCase(), overdue: Boolean(next && next < `${dateOnly(today)} 00:00` && !["WON", "LOST"].includes(lead.status)), overdueDays: Math.max(0, diff), dueBucket, followUpCount: data.leadFollowUps.filter((item) => item.leadId === lead.id).length, trialCount: data.trialBookings.filter((item) => item.leadId === lead.id).length };
}
function scopedLeads(data, role, userId) { return data.leads.filter((lead) => !lead.archived && (role === "admin" || lead.ownerCoachId === userId)); }
function trialCount(data, sessionId) { return data.trialBookings.filter((item) => item.sessionId === sessionId && item.status === "SCHEDULED").length; }
function handles(action) { return ["getCrmMeta", "getCrmDashboard", "listLeads", "checkLeadDuplicates", "getLead", "saveLead", "addLeadFollowUp", "assignLead", "moveLeadToPublic", "claimPublicLead", "archiveLead", "listTrials", "getTrial", "createTrial", "cancelTrial", "saveTrialFeedback", "convertLead", "getCrmStats"].includes(action); }

async function call(action, input, ctx) {
  const { data, role, userId, userName, today, uid, stamp, audit, save, createStudent, packages } = ctx;
  ensure(data, today);
  if (!handles(action)) return undefined;
  if (!["admin", "coach"].includes(role)) throw new Error("招生中心仅管理员和教练可用");
  if (action === "getCrmMeta") return { statuses: STATUS_LABELS, trialStatuses: TRIAL_STATUS_LABELS, sources: SOURCES, intentions: INTENTIONS, methods: METHODS, results: RESULTS, coaches: COACHES, packages };
  if (action === "getCrmDashboard") {
    const leads = scopedLeads(data, role, userId); const trials = data.trialBookings.filter((item) => leads.some((lead) => lead.id === item.leadId)); const completed = trials.filter((item) => item.status === "COMPLETED"); const won = leads.filter((item) => item.status === "WON");
    const todayRows = { newLeads: leads.filter((item) => isToday(item.createdAt, today)).length, due: leads.filter((item) => isToday(item.nextFollowUpAt, today)).length, scheduled: trials.filter((item) => item.status === "SCHEDULED" && isToday(item.trialDate, today)).length, trials: trials.filter((item) => item.status === "COMPLETED" && isToday(item.trialDate, today)).length, won: won.filter((item) => isToday(item.convertedAt, today)).length };
    const month = { newLeads: leads.filter((item) => isMonth(item.createdAt, today)).length, trials: completed.filter((item) => isMonth(item.trialDate, today)).length, won: won.filter((item) => isMonth(item.convertedAt, today)).length, amount: won.filter((item) => isMonth(item.convertedAt, today)).reduce((sum, item) => sum + Number(item.dealAmount || 0), 0) }; month.conversionRate = completed.length ? Math.round(won.length / completed.length * 100) : 0;
    const order = ["NEW", "CONTACTED", "TRIAL_SCHEDULED", "TRIAL_COMPLETED", "INTERESTED", "WON"]; const funnel = order.map((status) => ({ status, label: STATUS_LABELS[status], count: leads.filter((item) => item.status === status).length })); funnel.push({ status: "FORMAL", label: "正式学员", count: leads.filter((item) => item.convertedStudentId).length });
    return { today: todayRows, month, funnel: funnel.map((item) => ({ ...item, width: Math.min(100, Math.max(3, item.count * 12)) })), overdue: leads.filter((item) => decorateLead(data, item, today).overdue).length, publicCount: data.leads.filter((item) => item.status === "PUBLIC" && !item.archived).length, recent: leads.slice().sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, 5).map((item) => decorateLead(data, item, today)) };
  }
  if (action === "listLeads") {
    let rows = input.view === "public" ? data.leads.filter((item) => item.status === "PUBLIC" && !item.archived) : scopedLeads(data, role, userId);
    if (input.view === "won") rows = rows.filter((item) => item.status === "WON");
    if (input.view === "due") rows = rows.filter((item) => item.nextFollowUpAt && item.nextFollowUpAt.slice(0, 10) <= addDays(today, 7) && !["WON", "LOST"].includes(item.status));
    if (input.query) { const q = String(input.query).toLowerCase(); rows = rows.filter((item) => [item.childName, item.parentName, item.mobile].some((value) => String(value || "").toLowerCase().includes(q))); }
    ["status", "intentionLevel", "source", "interestedProgram", "ownerCoachId"].forEach((key) => { if (input[key]) rows = rows.filter((item) => item[key] === input[key]); });
    if (input.createdStart) rows = rows.filter((item) => dateOnly(item.createdAt) >= input.createdStart);
    if (input.createdEnd) rows = rows.filter((item) => dateOnly(item.createdAt) <= input.createdEnd);
    const sort = input.sort || "created"; rows.sort((a, b) => sort === "followed" ? String(b.lastFollowUpAt).localeCompare(String(a.lastFollowUpAt)) : sort === "oldest" ? String(a.lastFollowUpAt || a.createdAt).localeCompare(String(b.lastFollowUpAt || b.createdAt)) : sort === "next" ? String(a.nextFollowUpAt || "9999").localeCompare(String(b.nextFollowUpAt || "9999")) : String(b.createdAt).localeCompare(String(a.createdAt)));
    return rows.map((item) => decorateLead(data, item, today));
  }
  if (action === "checkLeadDuplicates") {
    const mobile = normalizedMobile(input.mobile); const leads = data.leads.filter((item) => item.id !== input.id && normalizedMobile(item.mobile) === mobile).map((item) => ({ type: "lead", id: item.id, name: item.childName, parentName: item.parentName, status: STATUS_LABELS[item.status] })); const students = data.students.filter((item) => normalizedMobile(item.guardianPhone) === mobile).map((item) => ({ type: "student", id: item.id, name: item.name, parentName: item.guardianName, status: "正式学员" })); return [...leads, ...students];
  }
  if (action === "getLead") { const lead = data.leads.find((item) => item.id === input.id); if (!lead || !canAccessLead(lead, role, userId)) throw new Error("无权查看该线索"); return { ...decorateLead(data, lead, today), followUps: data.leadFollowUps.filter((item) => item.leadId === lead.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), trials: data.trialBookings.filter((item) => item.leadId === lead.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map((item) => ({ ...item, statusLabel: TRIAL_STATUS_LABELS[item.status] })) }; }
  if (action === "saveLead") {
    const payload = { ...(input.lead || {}) }; if (!payload.childName || !payload.parentName || !/^1\d{10}$/.test(normalizedMobile(payload.mobile)) || !payload.source) throw new Error("请完整填写必填项"); let lead;
    if (payload.id) { lead = data.leads.find((item) => item.id === payload.id); if (!lead || !canAccessLead(lead, role, userId) || lead.status === "PUBLIC") throw new Error("无权修改该线索"); if (role === "coach") { payload.ownerCoachId = userId; payload.ownerCoachName = userName; } Object.assign(lead, payload, { updatedAt: stamp() }); }
    else { if (role === "coach") { payload.ownerCoachId = userId; payload.ownerCoachName = userName; } lead = { ...payload, id: uid("l"), status: payload.status || "NEW", intentionLevel: payload.intentionLevel || "B", tags: payload.tags || [], trialStatus: "", createdBy: userId, createdAt: stamp(), updatedAt: stamp(), convertedStudentId: "", convertedAt: "" }; data.leads.unshift(lead); }
    audit(data, role, payload.id ? "updateLead" : "createLead", "lead", lead.id, lead.childName); save(data); return { id: lead.id };
  }
  if (action === "addLeadFollowUp") { const lead = data.leads.find((item) => item.id === input.leadId); if (!lead || !canAccessLead(lead, role, userId) || lead.status === "PUBLIC") throw new Error("无权跟进该线索"); const item = { id: uid("lf"), leadId: lead.id, method: input.method, result: input.result, content: String(input.content || "").trim(), nextFollowUpAt: input.nextFollowUpAt || "", operatorId: userId, operatorName: userName, createdAt: stamp() }; if (!item.content) throw new Error("请填写跟进内容"); data.leadFollowUps.unshift(item); lead.lastFollowUpAt = item.createdAt; lead.nextFollowUpAt = item.nextFollowUpAt; if (input.result === "预约体验课") lead.status = "TRIAL_SCHEDULED"; else if (input.result === "意向报名") lead.status = "INTERESTED"; else if (input.result === "无意向") lead.status = "LOST"; else if (lead.status === "NEW") lead.status = "CONTACTED"; lead.updatedAt = stamp(); audit(data, role, "addLeadFollowUp", "lead", lead.id, item.result); save(data); return { id: item.id }; }
  if (action === "assignLead") { if (role !== "admin") throw new Error("仅管理员可分配线索"); const lead = data.leads.find((item) => item.id === input.id); const coach = COACHES.find((item) => item.id === input.ownerCoachId); if (!lead || !coach) throw new Error("分配信息无效"); lead.ownerCoachId = coach.id; lead.ownerCoachName = coach.name; if (lead.status === "PUBLIC") lead.status = "CONTACTED"; lead.updatedAt = stamp(); audit(data, role, "assignLead", "lead", lead.id, coach.name); save(data); return { ok: true }; }
  if (action === "moveLeadToPublic") { if (role !== "admin") throw new Error("仅管理员可放入公海"); const lead = data.leads.find((item) => item.id === input.id); if (!lead) throw new Error("线索不存在"); lead.ownerCoachId = ""; lead.ownerCoachName = ""; lead.status = "PUBLIC"; lead.updatedAt = stamp(); audit(data, role, "moveLeadToPublic", "lead", lead.id, lead.childName); save(data); return { ok: true }; }
  if (action === "claimPublicLead") { const lead = data.leads.find((item) => item.id === input.id); if (!lead || lead.status !== "PUBLIC" || lead.ownerCoachId) throw new Error("该线索已被其他教练领取"); lead.ownerCoachId = userId; lead.ownerCoachName = userName; lead.status = "CONTACTED"; lead.updatedAt = stamp(); audit(data, role, "claimPublicLead", "lead", lead.id, userName); save(data); return { ok: true }; }
  if (action === "archiveLead") { if (role !== "admin") throw new Error("仅管理员可归档"); const lead = data.leads.find((item) => item.id === input.id); lead.archived = true; lead.updatedAt = stamp(); audit(data, role, "archiveLead", "lead", lead.id, lead.childName); save(data); return { ok: true }; }
  if (action === "listTrials") { const leads = scopedLeads(data, role, userId); return data.trialBookings.filter((item) => leads.some((lead) => lead.id === item.leadId)).sort((a, b) => String(b.trialDate).localeCompare(String(a.trialDate))).map((item) => ({ ...item, statusLabel: TRIAL_STATUS_LABELS[item.status], lead: decorateLead(data, data.leads.find((lead) => lead.id === item.leadId), today) })); }
  if (action === "getTrial") { const trial = data.trialBookings.find((item) => item.id === input.id); const lead = trial && data.leads.find((item) => item.id === trial.leadId); if (!trial || !canAccessLead(lead, role, userId)) throw new Error("无权查看体验课"); return { ...trial, statusLabel: TRIAL_STATUS_LABELS[trial.status], lead: decorateLead(data, lead, today) }; }
  if (action === "createTrial") { const lead = data.leads.find((item) => item.id === input.leadId); if (!lead || !canAccessLead(lead, role, userId) || lead.status === "PUBLIC") throw new Error("无权预约该线索"); const session = data.sessions.find((item) => item.id === input.sessionId); const clubClass = data.classes.find((item) => item.id === (input.classId || (session || {}).classId)); if (!session && !clubClass) throw new Error("请选择体验课课程或班级"); if (session) { const formal = (data.classMembers || []).filter((item) => item.classId === session.classId && item.status === "ACTIVE").length; if (formal + trialCount(data, session.id) >= Number(session.capacity || 0)) throw new Error("本节课程体验课名额已满"); }
    const item = { id: uid("tb"), leadId: lead.id, childName: lead.childName, classId: (session || {}).classId || clubClass.id, className: (clubClass || {}).name || "", sessionId: (session || {}).id || "", coachId: input.coachId || lead.ownerCoachId, coachName: input.coachName || (session || {}).coachName || lead.ownerCoachName, venueName: input.venueName || (session || {}).venue || (clubClass || {}).venue || "", trialDate: input.trialDate || (session || {}).date, status: "SCHEDULED", attendanceStatus: "unmarked", remark: input.remark || "", createdBy: userId, createdAt: stamp(), updatedAt: stamp() }; data.trialBookings.unshift(item); lead.status = "TRIAL_SCHEDULED"; lead.trialStatus = "SCHEDULED"; lead.updatedAt = stamp(); audit(data, role, "createTrial", "trial", item.id, lead.childName); save(data); return { id: item.id }; }
  if (action === "cancelTrial") { const trial = data.trialBookings.find((item) => item.id === input.id); const lead = trial && data.leads.find((item) => item.id === trial.leadId); if (!trial || !canAccessLead(lead, role, userId)) throw new Error("无权取消体验课"); if (trial.status !== "SCHEDULED") throw new Error("当前体验课不可取消"); trial.status = "CANCELLED"; trial.cancelReason = String(input.reason || "计划调整"); trial.updatedAt = stamp(); const active = data.trialBookings.some((item) => item.leadId === lead.id && item.id !== trial.id && item.status === "SCHEDULED"); if (!active && lead.status === "TRIAL_SCHEDULED") { lead.status = "CONTACTED"; lead.trialStatus = "CANCELLED"; lead.updatedAt = stamp(); } audit(data, role, "cancelTrial", "trial", trial.id, trial.cancelReason); save(data); return { ok: true }; }
  if (action === "saveTrialFeedback") { const trial = data.trialBookings.find((item) => item.id === input.id); const lead = trial && data.leads.find((item) => item.id === trial.leadId); if (!trial || !canAccessLead(lead, role, userId)) throw new Error("无权填写体验课反馈"); trial.feedback = input.feedback || {}; trial.recommendedClassId = input.recommendedClassId || ""; trial.status = "COMPLETED"; trial.attendanceStatus = trial.attendanceStatus === "unmarked" ? "present" : trial.attendanceStatus; trial.updatedAt = stamp(); lead.status = lead.status === "WON" ? "WON" : "TRIAL_COMPLETED"; lead.trialStatus = "COMPLETED"; lead.nextFollowUpAt = `${addDays(trial.trialDate || today, 1)} 10:00`; lead.updatedAt = stamp(); if (!data.leadFollowUps.some((item) => item.leadId === lead.id && item.content === "体验课后回访" && dateOnly(item.nextFollowUpAt) === dateOnly(lead.nextFollowUpAt))) data.leadFollowUps.unshift({ id: uid("lf"), leadId: lead.id, method: "其他", result: "等待回复", content: "体验课后回访", nextFollowUpAt: lead.nextFollowUpAt, operatorId: userId, operatorName: userName, createdAt: stamp() }); audit(data, role, "saveTrialFeedback", "trial", trial.id, lead.childName); save(data); return { ok: true, nextFollowUpAt: lead.nextFollowUpAt }; }
  if (action === "convertLead") { if (role !== "admin") throw new Error("仅管理员可转为正式学员"); if (!input.avatarUrl) throw new Error("请上传孩子本人照片"); const lead = data.leads.find((item) => item.id === input.id); if (!lead || lead.convertedStudentId) throw new Error("该线索已经转换"); const duplicate = data.students.find((item) => normalizedMobile(item.guardianPhone) === normalizedMobile(lead.mobile) || (item.name === lead.childName && item.birthDate === lead.birthday)); if (duplicate && !input.confirmDuplicate) return { duplicate: { id: duplicate.id, name: duplicate.name, guardianName: duplicate.guardianName } }; if ((input.classIds || []).some((classId) => (data.classes.find((item) => item.id === classId) || {}).classType === "ELITE")) throw new Error("CRM转正式学员只能进入普通班"); const pack = packages[input.packageId] || { lessons: Number(input.initialLessons || 0), amount: Number(input.amount || 0), name: "自定义课时" }; const created = await createStudent({ name: lead.childName, avatarUrl: input.avatarUrl, gender: lead.gender, birthDate: lead.birthday, guardianName: lead.parentName, guardianPhone: lead.mobile, emergencyContact: `${lead.parentName} ${lead.mobile}`, healthNotes: lead.remark || "无", remainingLessons: Number(input.initialLessons || pack.lessons || 0), classIds: input.classIds || [], school: lead.school, grade: lead.grade, crmLeadId: lead.id, source: lead.source, registrationDate: input.registrationDate || dateOnly(today), recruitmentOwnerId: input.ownerCoachId || lead.ownerCoachId, recruitmentOwnerName: input.ownerCoachName || lead.ownerCoachName }); lead.status = "WON"; lead.convertedStudentId = created.id; lead.convertedAt = stamp(); lead.dealAmount = Number(input.amount || pack.amount || 0); lead.registrationDate = input.registrationDate || dateOnly(today); lead.updatedAt = stamp(); audit(data, role, "convertLead", "lead", lead.id, created.id); save(data); return { id: created.id }; }
  if (action === "getCrmStats") { if (role !== "admin") throw new Error("仅管理员可查看公司招生统计"); const start = input.start || `${dateOnly(today).slice(0, 7)}-01`; const end = input.end || dateOnly(today); const within = (value) => dateOnly(value) >= start && dateOnly(value) <= end; const leads = data.leads.filter((item) => within(item.createdAt)); const trials = data.trialBookings.filter((item) => item.status === "COMPLETED" && within(item.trialDate)); const won = data.leads.filter((item) => item.status === "WON" && within(item.convertedAt)); const channels = SOURCES.map((source) => { const sourceLeads = leads.filter((item) => item.source === source); const ids = sourceLeads.map((item) => item.id); const sourceTrials = trials.filter((item) => ids.includes(item.leadId)); const sourceWon = won.filter((item) => item.source === source); return { source, leads: sourceLeads.length, trials: sourceTrials.length, won: sourceWon.length, rate: sourceLeads.length ? Math.round(sourceWon.length / sourceLeads.length * 100) : 0 }; }).filter((item) => item.leads); const coaches = COACHES.map((coach) => { const rows = leads.filter((item) => item.ownerCoachId === coach.id); const ids = rows.map((item) => item.id); const wins = won.filter((item) => item.ownerCoachId === coach.id).length; return { ...coach, leads: rows.length, contacted: rows.filter((item) => item.status !== "NEW").length, trials: trials.filter((item) => ids.includes(item.leadId)).length, won: wins, rate: rows.length ? Math.round(wins / rows.length * 100) : 0 }; }); return { summary: { leads: leads.length, trials: trials.length, won: won.length, rate: trials.length ? Math.round(won.length / trials.length * 100) : 0, amount: won.reduce((sum, item) => sum + Number(item.dealAmount || 0), 0) }, channels, coaches, start, end }; }
  throw new Error(`未实现CRM操作：${action}`);
}

function applyTrialAttendance(data, sessionId, records, ctx) {
  ensure(data, ctx.today); (records || []).forEach((record) => { const trial = data.trialBookings.find((item) => item.id === record.trialId && item.sessionId === sessionId); if (!trial) return; trial.attendanceStatus = record.status; trial.updatedAt = ctx.stamp(); if (record.status === "absent") trial.status = "NO_SHOW"; });
}

module.exports = { ensure, handles, call, trialCount, applyTrialAttendance, STATUS_LABELS, TRIAL_STATUS_LABELS, SOURCES, INTENTIONS, COACHES };
